// Note: only publicly-accessible bugs (those not in any group) will be
// listed when using this JavaScript format. This is to prevent malicious
// sites stealing information about secure bugs.
  
bugs = new Array; 

  bugs[491927] = [ 
      "--",
      "2009-05-14",
      "",
      "ashughes\x40mozilla.com",
      "location.bar\x40firefox.bugs",
      "normal",
      "2009-05-07",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Anthony Hughes",
      "ashughes\x40mozilla.com",
      "All",
      "[mozmill] Test for navigating to a URL using the location bar",
      "",
      "0",
      "ASSIGNED",
      "unspecified",
      "Location Bar and Autocomplete",
      "Anthony Hughes",
      "Firefox",
      "---",
      ""
  ];
  bugs[493083] = [ 
      "--",
      "2009-05-18",
      "",
      "ashughes\x40mozilla.com",
      "firefox\x40security.bugs",
      "normal",
      "2009-05-14",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Anthony Hughes",
      "ashughes\x40mozilla.com",
      "All",
      "[mozmill] Test for verifying pop-ups are blocked",
      "",
      "0",
      "NEW",
      "unspecified",
      "Security",
      "Anthony Hughes",
      "Firefox",
      "Firefox 3.5",
      ""
  ];
  bugs[493084] = [ 
      "--",
      "2009-05-18",
      "",
      "ashughes\x40mozilla.com",
      "firefox\x40security.bugs",
      "normal",
      "2009-05-14",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Anthony Hughes",
      "ashughes\x40mozilla.com",
      "All",
      "[mozmill] Test for verifying pop-ups are allowed",
      "",
      "0",
      "NEW",
      "unspecified",
      "Security",
      "Anthony Hughes",
      "Firefox",
      "Firefox 3.5",
      ""
  ];
  bugs[479920] = [ 
      "--",
      "2009-02-23",
      "",
      "dmose\x40mozilla.org",
      "message-reader\x40thunderbird.bugs",
      "normal",
      "2009-02-23",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Dan Mosedale (:dmose)",
      "ludovic\x40mozillamessaging.com",
      "All",
      "Running the CAPS test in mozmill generates an exception",
      "",
      "0",
      "NEW",
      "Trunk",
      "Message Reader UI",
      "Ludovic Hirlimann (:_Tsk_)",
      "Thunderbird",
      "---",
      ""
  ];
  bugs[487041] = [ 
      "--",
      "2009-05-10",
      "",
      "gary\x40mozillamessaging.com",
      "general\x40thunderbird.bugs",
      "normal",
      "2009-04-06",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Gary Kwong [:nth10sd]",
      "gary\x40mozillamessaging.com",
      "All",
      "Automate Thunderbird Litmus Tests using Mozmill",
      "",
      "0",
      "NEW",
      "Trunk",
      "General",
      "Gary Kwong [:nth10sd]",
      "Thunderbird",
      "---",
      ""
  ];
  bugs[492954] = [ 
      "--",
      "2009-05-18",
      "",
      "gary\x40mozillamessaging.com",
      "general\x40thunderbird.bugs",
      "normal",
      "2009-05-14",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Gary Kwong [:nth10sd]",
      "bugzilla\x40standard8.plus.com",
      "All",
      "Create a set of MozMill template\/shared functions for folder actions in Thunderbird",
      "",
      "0",
      "NEW",
      "unspecified",
      "General",
      "Mark Banner (:standard8)",
      "Thunderbird",
      "---",
      "WIP"
  ];
  bugs[474313] = [ 
      "--",
      "2009-02-03",
      "",
      "hskupin\x40gmail.com",
      "places\x40firefox.bugs",
      "normal",
      "2009-01-19",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Henrik Skupin [:whimboo]",
      "hskupin\x40gmail.com",
      "All",
      "[mozmill] test for adding bookmark to bookmarks menu",
      "",
      "0",
      "ASSIGNED",
      "Trunk",
      "Places",
      "Henrik Skupin [:whimboo]",
      "Firefox",
      "---",
      "Patch v3.1 (checked-in) - review+, review+, review-"
  ];
  bugs[479314] = [ 
      "P2",
      "2009-05-11",
      "",
      "hskupin\x40gmail.com",
      "private.browsing\x40firefox.bugs",
      "normal",
      "2009-02-19",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Henrik Skupin [:whimboo]",
      "hskupin\x40gmail.com",
      "All",
      "[mozmill] test for entering private browsing mode",
      "",
      "0",
      "ASSIGNED",
      "3.5 Branch",
      "Private Browsing",
      "Henrik Skupin [:whimboo]",
      "Firefox",
      "---",
      ""
  ];
  bugs[493120] = [ 
      "--",
      "2009-05-20",
      "",
      "hskupin\x40gmail.com",
      "content\x40qmo.bugs",
      "normal",
      "2009-05-14",
      "",
      "Other",
      "",
      "",
      "All",
      "---",
      "Henrik Skupin [:whimboo]",
      "hskupin\x40gmail.com",
      "All",
      "Add documentation how to create MozMill tests for Firefox",
      "",
      "0",
      "ASSIGNED",
      "unspecified",
      "Content",
      "Henrik Skupin [:whimboo]",
      "quality.mozilla.org",
      "---",
      ""
  ];
  bugs[489770] = [ 
      "P2",
      "2009-05-19",
      "",
      "joshmoz\x40gmail.com",
      "cocoa\x40widget.bugs",
      "normal",
      "2009-04-23",
      "",
      "Components",
      "",
      "",
      "Mac OS X",
      "---",
      "Josh Aas",
      "hskupin\x40gmail.com",
      "All",
      "Mozmill recorder and inspector don\'t work with the menubar and it sub menus on OS X",
      "",
      "0",
      "NEW",
      "Trunk",
      "Widget: Cocoa",
      "Henrik Skupin [:whimboo]",
      "Core",
      "---",
      ""
  ];
  bugs[458352] = [ 
      "--",
      "2009-05-14",
      "",
      "ludovic\x40mozillamessaging.com",
      "build-config\x40mail.bugs",
      "normal",
      "2008-10-03",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Ludovic Hirlimann (:_Tsk_)",
      "bugzilla\x40standard8.plus.com",
      "All",
      "Integrate Mail Bloat Tests with MozMill",
      "",
      "1",
      "NEW",
      "Trunk",
      "Build Config",
      "Mark Banner (:standard8)",
      "MailNews Core",
      "---",
      "andrew\'s mozmill driver as it exists, based on standard8\'s - review+, WIP v2 - review+, move file v3 - review+, [checked in] patch addressing review comments - review+"
  ];
  bugs[456451] = [ 
      "P4",
      "2009-04-14",
      "",
      "mrogers\x40mozilla.com",
      "mozmill\x40testing.bugs",
      "minor",
      "2008-09-22",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Mikeal Rogers [:mikeal] (mrogers\x40)",
      "farhad\x40flock.com",
      "All",
      "Need to stop\/start DOM explorer to discover ID\/Elements for sub-menu options",
      "[mozmill-future]",
      "0",
      "ASSIGNED",
      "unspecified",
      "Mozmill",
      "Farhad Sabeti",
      "Testing",
      "---",
      ""
  ];
  bugs[474486] = [ 
      "P1",
      "2009-05-03",
      "",
      "mrogers\x40mozilla.com",
      "mozmill\x40testing.bugs",
      "major",
      "2009-01-20",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Mikeal Rogers [:mikeal] (mrogers\x40)",
      "hskupin\x40gmail.com",
      "All",
      "Dynamic (realtime) menu access needed for MenuAPI",
      "[mozmill-1.2]",
      "0",
      "ASSIGNED",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[489474] = [ 
      "--",
      "16:01:00",
      "",
      "mrogers\x40mozilla.com",
      "video.audio\x40core.bugs",
      "normal",
      "2009-04-21",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Mikeal Rogers [:mikeal] (mrogers\x40)",
      "mrogers\x40mozilla.com",
      "All",
      "[mozmill] Write automated tests for user generated video controls",
      "",
      "0",
      "ASSIGNED",
      "1.9.1 Branch",
      "Video\/Audio",
      "Mikeal Rogers [:mikeal] (mrogers\x40)",
      "Core",
      "---",
      "video tests - review-"
  ];
  bugs[457265] = [ 
      "P1",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2008-09-26",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Integrate Mozmill into build system",
      "[mozmill-1.2]",
      "1",
      "NEW",
      "unspecified",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      "Add buildbot configs. for Mozmill, round 1 - review-"
  ];
  bugs[469393] = [ 
      "P3",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2008-12-12",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "twalker\x40mozilla.com",
      "All",
      "Make it possible to stop(pause)\/restart recorder within building a test case.",
      "[mozmill-future]",
      "0",
      "NEW",
      "unspecified",
      "Mozmill",
      "Tracy Walker",
      "Testing",
      "---",
      ""
  ];
  bugs[472099] = [ 
      "P4",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-01-05",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Create template library which can be used for new test files",
      "[mozmill-future]",
      "0",
      "REOPENED",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[472130] = [ 
      "P4",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-01-05",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Make MozMill ready for localization",
      "[mozmill-future]",
      "0",
      "NEW",
      "1.9.1 Branch",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[472131] = [ 
      "P5",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "minor",
      "2009-01-05",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Selection of elements name which will be copied to clipboard is not correctly shown inside the inspector output",
      "[mozmill-future]",
      "0",
      "NEW",
      "1.9.1 Branch",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "Future",
      ""
  ];
  bugs[472737] = [ 
      "P4",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-01-08",
      "",
      "Components",
      "",
      "",
      "Mac OS X",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "x86",
      "Mozmill menu item not visible when a non-browser window has focus",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "Future",
      ""
  ];
  bugs[472898] = [ 
      "P4",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-01-09",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Make it easier to add actions by accessing the available command list via context menu",
      "[mozmill-future]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[473154] = [ 
      "--",
      "2009-01-12",
      "",
      "nobody\x40mozilla.org",
      "httpd.js\x40testing.bugs",
      "minor",
      "2009-01-12",
      "",
      "Components",
      "",
      "",
      "Mac OS X",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "x86",
      "Warning when trying to run a local HttpServer with MozMill: undefined property Ci.nsIHttpServer",
      "",
      "0",
      "NEW",
      "Trunk",
      "httpd.js",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[474057] = [ 
      "P4",
      "2009-04-14",
      "meta",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-01-16",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "[meta] UI overhaul for MozMill",
      "[mozmill-future]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[475797] = [ 
      "P1",
      "2009-04-22",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2009-01-28",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "waitForPageLoad isn\'t fully reliable (e.g. for slow connections)",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[477079] = [ 
      "P1",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "blocker",
      "2009-02-05",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "ctalbert\x40mozilla.com",
      "All",
      "Templetized Trees cannot be automated",
      "[mozmill-future]",
      "0",
      "NEW",
      "unspecified",
      "Mozmill",
      "Clint Talbert ( :ctalbert )",
      "Testing",
      "---",
      ""
  ];
  bugs[477135] = [ 
      "P3",
      "2009-04-09",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-02-05",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Support for delayed action (element has to exist) when clicking an element",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[478040] = [ 
      "P4",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-02-11",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "No error thrown if RELATIVE_ROOT for modules doesn\'t exist",
      "[mozmill-future]",
      "0",
      "REOPENED",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[479365] = [ 
      "P5",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "minor",
      "2009-02-19",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Darken cursor to make it more prominent",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[479366] = [ 
      "P4",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-02-19",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Add option to make white-space characters visible",
      "[mozmill-future]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[479368] = [ 
      "P4",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-02-19",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Switching panes and returning to the editor resets the view to top",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[479370] = [ 
      "P3",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2009-02-19",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Accessibility for new menus is completely limited",
      "[mozmill-future]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[480085] = [ 
      "P5",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "minor",
      "2009-02-24",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Reversed tabbing order in inspector overlay",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[480978] = [ 
      "P4",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-03-02",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "MozMill window is always placed on the primary screen for multi-monitor setup",
      "[mozmill-future]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[481130] = [ 
      "P4",
      "2009-04-22",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2009-03-02",
      "",
      "Components",
      "",
      "",
      "Mac OS X",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "x86",
      "Unresponsive script warnings when running tests from a directory",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[481132] = [ 
      "P4",
      "2009-04-09",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-03-02",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Deactivate shortcuts when MozMill is in special states",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[481588] = [ 
      "P5",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "minor",
      "2009-03-04",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "A bunch of warnings in mozmill.html are shown in the error console when running a test",
      "[mozmill-future]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[482359] = [ 
      "P2",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-03-09",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Recorder is not able to recognize metadata of mouse clicks (right, middle, Ctrl...)",
      "[mozmill-1.2]",
      "1",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[483720] = [ 
      "--",
      "2009-03-16",
      "",
      "nobody\x40mozilla.org",
      "general\x40testing.bugs",
      "enhancement",
      "2009-03-16",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "archaeopteryx\x40coole-files.de",
      "All",
      "Combine mozmill and leak gauge",
      "",
      "0",
      "NEW",
      "unspecified",
      "General",
      "",
      "Testing",
      "---",
      ""
  ];
  bugs[484564] = [ 
      "--",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-03-21",
      "",
      "Components",
      "",
      "",
      "Mac OS X",
      "---",
      "Nobody; OK to take it and work on it",
      "wlaver\x40gmail.com",
      "x86",
      "Cannot playback recorded events in firebug\/pixel perfect",
      "",
      "0",
      "UNCONFIRMED",
      "unspecified",
      "Mozmill",
      "Mike Buckley",
      "Testing",
      "---",
      ""
  ];
  bugs[485009] = [ 
      "--",
      "2009-03-24",
      "",
      "nobody\x40mozilla.org",
      "rss.preview\x40firefox.bugs",
      "normal",
      "2009-03-24",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "[mozmill] Test for refreshing a Live Bookmark",
      "",
      "0",
      "NEW",
      "3.5 Branch",
      "RSS Discovery and Preview",
      "Henrik Skupin [:whimboo]",
      "Firefox",
      "---",
      ""
  ];
  bugs[486407] = [ 
      "P1",
      "Tue 21:14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "blocker",
      "2009-04-01",
      "",
      "Components",
      "",
      "",
      "Windows XP",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "x86",
      "Switching panes in preferences dialog doesn\'t work on Windows",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[487051] = [ 
      "P3",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-06",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Add a stop feature to MozMill",
      "[mozmill-future]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[487380] = [ 
      "--",
      "2009-04-15",
      "meta",
      "nobody\x40mozilla.org",
      "general\x40thunderbird.bugs",
      "normal",
      "2009-04-08",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "ludovic\x40mozillamessaging.com",
      "All",
      "Mozmill features and bugs  needed for Thunderbird",
      "",
      "1",
      "NEW",
      "Trunk",
      "General",
      "Ludovic Hirlimann (:_Tsk_)",
      "Thunderbird",
      "---",
      ""
  ];
  bugs[487584] = [ 
      "P3",
      "04:51:43",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-09",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Click on buttons which are embedded in widgets does not remove focus (e.g. location bar, search bar)",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[487588] = [ 
      "P2",
      "2009-04-14",
      "dataloss",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "critical",
      "2009-04-09",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Undo stack of editor cleared when running a test (save, save as)",
      "[mozmill-future]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[487591] = [ 
      "P3",
      "2009-05-06",
      "testcase",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2009-04-09",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Inspector doesn\'t stop inspecting when clear icon in search widget is clicked",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[487701] = [ 
      "P1",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2009-04-09",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Allow several restarts for a single test",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[487755] = [ 
      "--",
      "Tue 17:25",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-09",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "adesai\x40mozilla.com",
      "All",
      "Testscripts from MozMill TestDay",
      "",
      "0",
      "NEW",
      "unspecified",
      "Mozmill",
      "Aakash Desai",
      "Testing",
      "---",
      "Test Back\/Forward buttons (checked-in) - review+, review-, review-, review-, review-, review-, review-, review-, review-, review-, review-, review-, review-, review-, review? (ctalbert\x40mozilla.com)"
  ];
  bugs[488352] = [ 
      "P5",
      "2009-04-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "minor",
      "2009-04-14",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "tchung\x40mozilla.com",
      "All",
      "Add tooltips to editor controls on mozmill UI",
      "[mozmill-1.2]",
      "0",
      "NEW",
      "unspecified",
      "Mozmill",
      "Tony Chung [:tchung]",
      "Testing",
      "---",
      ""
  ];
  bugs[488492] = [ 
      "--",
      "2009-04-22",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-15",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "jmaher\x40mozilla.com",
      "All",
      "update the template to set elementslib to mozmill.elementslib",
      "",
      "0",
      "NEW",
      "unspecified",
      "Mozmill",
      "Joel Maher",
      "Testing",
      "---",
      ""
  ];
  bugs[488503] = [ 
      "P4",
      "2009-04-15",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-15",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "adesai\x40mozilla.com",
      "All",
      "Ctrl\/Cmd+A instantiates Save File Marker \"*\"",
      "",
      "0",
      "NEW",
      "unspecified",
      "Mozmill",
      "Aakash Desai",
      "Testing",
      "---",
      ""
  ];
  bugs[488778] = [ 
      "P3",
      "2009-04-21",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-16",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Execution of test stucks at the beginning after browser window was closed and reopened",
      "",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[488823] = [ 
      "P4",
      "2009-05-05",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-17",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Inspector\/Recorder should only obey label attributes for elements if no other path is available",
      "",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[489818] = [ 
      "P2",
      "2009-04-23",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2009-04-23",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Collector should only collect folder starting with test",
      "",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[490411] = [ 
      "--",
      "2009-04-28",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-27",
      "",
      "Components",
      "",
      "",
      "Windows XP",
      "---",
      "Nobody; OK to take it and work on it",
      "dongdongdeng\x40hotmail.com",
      "x86",
      "elementslib.Lookup(document, expression) does not work for annon element",
      "",
      "0",
      "UNCONFIRMED",
      "unspecified",
      "Mozmill",
      "dongdongdeng",
      "Testing",
      "---",
      ""
  ];
  bugs[490412] = [ 
      "--",
      "2009-04-28",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-04-27",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "dongdongdeng\x40hotmail.com",
      "All",
      "ID.prototype.getNodeForDocument = function (s) { return this.document.getElementById(s);}",
      "",
      "0",
      "UNCONFIRMED",
      "unspecified",
      "Mozmill",
      "dongdongdeng",
      "Testing",
      "---",
      ""
  ];
  bugs[490548] = [ 
      "P1",
      "2009-05-14",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "blocker",
      "2009-04-28",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "A MozMill test should fail if an element we operate on is not visible",
      "",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[491200] = [ 
      "P3",
      "2009-05-03",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-05-03",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Mozmill should not use anonymous function names",
      "",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[491216] = [ 
      "P2",
      "2009-05-03",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2009-05-03",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Mozmill doesn\'t work in offline mode (exceptions during startup)",
      "",
      "0",
      "NEW",
      "Trunk",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[491952] = [ 
      "--",
      "2009-05-19",
      "",
      "nobody\x40mozilla.org",
      "preferences\x40firefox.bugs",
      "normal",
      "2009-05-07",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "adesai\x40mozilla.com",
      "All",
      "[mozmill] - Set Home Page to current page",
      "",
      "0",
      "NEW",
      "unspecified",
      "Preferences",
      "Aakash Desai",
      "Firefox",
      "---",
      ""
  ];
  bugs[491957] = [ 
      "--",
      "2009-05-15",
      "",
      "nobody\x40mozilla.org",
      "preferences\x40firefox.bugs",
      "normal",
      "2009-05-07",
      "",
      "Client Software",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "adesai\x40mozilla.com",
      "All",
      "[mozmill] - Main Menu of Options (Preferences)",
      "",
      "0",
      "NEW",
      "unspecified",
      "Preferences",
      "Aakash Desai",
      "Firefox",
      "---",
      ""
  ];
  bugs[492055] = [ 
      "P4",
      "2009-05-08",
      "testcase",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-05-08",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Sometimes element inspection of radiogroup doesn\'t detect correct radiobutton",
      "",
      "0",
      "NEW",
      "1.9.1 Branch",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[492136] = [ 
      "P2",
      "2009-05-11",
      "testcase",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-05-08",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "If test in modal dialog fails no timeout is fired by Mozmill",
      "",
      "0",
      "NEW",
      "1.9.1 Branch",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[493039] = [ 
      "P3",
      "2009-05-18",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "major",
      "2009-05-14",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Need better API for assertValue and assertText",
      "",
      "0",
      "NEW",
      "1.9.1 Branch",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      ""
  ];
  bugs[493671] = [ 
      "--",
      "2009-05-20",
      "",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "critical",
      "2009-05-18",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "ashughes\x40mozilla.com",
      "All",
      "[mozmill] Mozmill ignores prefs, does not reflect manual behaviour",
      "",
      "0",
      "NEW",
      "unspecified",
      "Mozmill",
      "Anthony Hughes",
      "Testing",
      "---",
      ""
  ];
  bugs[493787] = [ 
      "--",
      "2009-05-20",
      "",
      "nobody\x40mozilla.org",
      "preferences\x40firefox.bugs",
      "normal",
      "2009-05-19",
      "",
      "Client Software",
      "",
      "",
      "Mac OS X",
      "---",
      "Nobody; OK to take it and work on it",
      "adesai\x40mozilla.com",
      "x86",
      "[mozmill] - Restore Home Page to default",
      "",
      "0",
      "NEW",
      "unspecified",
      "Preferences",
      "Aakash Desai",
      "Firefox",
      "---",
      ""
  ];
  bugs[493851] = [ 
      "--",
      "2009-05-20",
      "",
      "nobody\x40mozilla.org",
      "preferences\x40firefox.bugs",
      "normal",
      "2009-05-19",
      "",
      "Client Software",
      "",
      "",
      "Mac OS X",
      "---",
      "Nobody; OK to take it and work on it",
      "adesai\x40mozilla.com",
      "x86",
      "[mozmill] - Options (Preferences) dialog state retention",
      "",
      "0",
      "NEW",
      "unspecified",
      "Preferences",
      "Aakash Desai",
      "Firefox",
      "---",
      ""
  ];
  bugs[494071] = [ 
      "--",
      "15:17:28",
      "regression",
      "nobody\x40mozilla.org",
      "mozmill\x40testing.bugs",
      "blocker",
      "2009-05-20",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Nobody; OK to take it and work on it",
      "hskupin\x40gmail.com",
      "All",
      "Using keypress without modifiers doesn\'t insert characters into text fields",
      "",
      "0",
      "NEW",
      "unspecified",
      "Mozmill",
      "Henrik Skupin [:whimboo]",
      "Testing",
      "---",
      "example patch for better keypress handling (checked-in), Follow-up patch against extension folder"
  ];
  bugs[479500] = [ 
      "--",
      "2009-04-17",
      "",
      "twalker\x40mozilla.com",
      "mozmill\x40testing.bugs",
      "normal",
      "2009-02-20",
      "",
      "Components",
      "",
      "",
      "All",
      "---",
      "Tracy Walker",
      "twalker\x40mozilla.com",
      "All",
      "Mozmill smoketest case writing assigned to Tracy",
      "",
      "0",
      "ASSIGNED",
      "1.9.1 Branch",
      "Mozmill",
      "Tracy Walker",
      "Testing",
      "---",
      ""
  ];

if (window.buglistCallback) {
  buglistCallback(bugs);
}